Crud/Crud/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls'))
]

Crud/usuarios/urls.py
from django.urls import path
from usuarios import views as v


app_name = 'aplication'
urlpatterns = [
    path('', v.inicio, name = 'inicio'),
    path('detail<int:id>/', v.detail , name = 'detail'),
    path('create/', v.create_usuario, name = 'create'),
    path('update_<int:id>/', v.update_usuario, name = 'update'),
    path('delete_<int:id>/', v.delete_usuario, name = 'delete')
]

Crud/usuarios/models.py
from django.db import models

class Usuario(models.Model):
    name = models.CharField(max_length = 100 , blank = False , null = False)
    empresa = models.CharField(max_length = 100 , blank = False , null = False)

    def __str__(self):
        return self.name

Crud/usuarios/forms.py
from django.forms import ModelForm
from .models import Usuario

class UsuarioForm(ModelForm):
    class Meta:
        model = Usuario
        fields = '__all__'

Crud/usuarios/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Usuario
from .forms import UsuarioForm

def inicio(request):
    usuarios = Usuario.objects.all()
    contexto = {
        'usuarios' : usuarios
    }
    return render(request, 'usuarios/index.html', contexto)


def detail(request, id):
    detail_usuario = get_object_or_404(Usuario, pk = id)
    context = {
        'detail_usuario' : detail_usuario
    }
    return render(request, 'usuarios/detail.html', context)

def create_usuario(request):
    if request.method == "POST":
        usuario_form = UsuarioForm(request.POST)
        if usuario_form.is_valid():
            usuario_form.save()
            return redirect('aplication:inicio')
    else :
        usuario_form = UsuarioForm()
        return render(request, 'usuarios/create.html', {'usuario_form': usuario_form})

def update_usuario(request, id):
    usuario= get_object_or_404(Usuario, id = id)
    if request.method == "POST" :
        usuario_form = UsuarioForm(request.POST, instance = usuario)
        if usuario_form.is_valid():
                usuario_form.save()
                return redirect('aplication:inicio')
    else :
        usuario_form = UsuarioForm()
        return render(request, 'usuarios/editar.html', {'usuario_form': usuario_form})

def delete_usuario(request, id):
    usuario= get_object_or_404(Usuario, id = id)

    if usuario :
        usuario.delete()

    return redirect('aplication:inicio')

Crud/usuarios/templates/usuarios/create.html
<form method="POST">
  {% csrf_token %}

{{ usuario_form.as_p }}
  <button type="submit"> Create </button>
</form>

Crud/usuarios/templates/usuarios/detail.html
<div class="container">
  <p> {{ detail_usuario.id }}</p>
  <p> {{ detail_usuario.name }}</p>
  <p> {{ detail_usuario.empresa }}</p>
</div>

Crud/usuarios/templates/usuarios/editar.html
<form method="POST">
  {% csrf_token %}

{{ usuario_form.as_p }}
  <button type="submit"> Guardar </button>
</form>

Crud/usuarios/templates/usuarios/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>index</title>
    <link rel="stylesheet" href="{% static '/bootstrap.min.css' %}">
  </head>
  <body>

    <div class="container">

        <a href="{% url 'aplication:create' %}" class="btn btn-outline-dark mt-5">Crear Nuevo</a>

        <table class="table table-bordered table-info mt-5 text-center">
        <thead>
            <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Empresa</th>
            </tr>
        </thead>
        <tbody>
            {% for usuario in usuarios %}
                <tr>
                    <th>{{ usuario.id }}</th>
                    <td>{{ usuario.name }}</td>
                    <td>{{ usuario.empresa }}</td>
                    <td>
                        <a href="{% url 'aplication:detail' usuario.id %}" class="btn btn-danger">Ver mas</a>
                        <a href="{% url 'aplication:update' usuario.id %}" class="btn btn-success">Editar</a>
                        <a href="{% url 'aplication:delete' usuario.id %}" class="btn btn-primary">Eliminar</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
        </table>


    </div>


  </body>
</html>